name: reminder_assistant
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  firebase_core: ^4.2.1
  firebase_auth: any
  google_sign_in: ^6.1.5
  flutter:
    sdk: flutter
  flutter_datetime_picker: ^1.5.1
  go_router: ^16.1.0
  intl: ^0.17.0
  provider: ^6.1.5+1
  time_picker_spinner: ^1.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
